### ISSUE TITLE
Keep consistency @types/node with actual node.js version 

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#105]
https://github.com/mobu-of-the-world/mobu/pull/103#issuecomment-827528957

---

What is the 15.x providing strategy... 🤔  Keeping 14.x is better? Or use 16.x?

https://nodejs.org/ja/about/releases/

<img width="840" alt="スクリーンショット 2021-04-28 22 24 35" src="https://user-images.githubusercontent.com/1180335/116411297-8a98b800-a870-11eb-92a4-5e07f464df3c.png">

**Comment by pankona** [comment]
@kachick 

I think ideally we should use active LTS (v14) but we are on the cutting edge on this project let's use v16 or latest and let's report issues if we find some problem with it. How about it?

**Comment by kachick** [comment]
> we are on the cutting edge on this project let's use v16 or latest and let's report issues if we find some problem with it. How about it?

Perfectly agreed. 👍  This project is the  front-runner of the web-frontend. We should use latest Node.js.

**Comment by pankona** [comment]
@kachick 

I wonder it is hard to keep using latest nodejs if we use react-script. Is it time to eject!?

**Comment by kachick** [comment]
Thanks for your addressing!
Hmm... In my understanding, keeping to use react-script might be better way 🤔

I think we should choice one of two ways.

* We are a front-runner. So immediately `reject` and use latest Node.js
* When plans to provide Enterprise Edition, keeping react-script might be better

I'm leave it to you 😉

**Comment by kachick** [comment]
https://github.com/mobu-of-the-world/mobu/pull/392 did this
