### ISSUE TITLE
mobu v2

### ISSUE THREAD

**Issue by pankona** [mobu-of-the-world/mobu#292]
mobu v2 構想

## 新機能

- 複数人数で同じセッションを共有する機能をつける
  - 参加者の間で経過時間とドライバー・ナビゲーター情報をリアルタイムに共有できるようにする

## v2 にする理由

- URL を変えたい
  - 参加者間の情報同期には firebase の realtime database を使おうと思っている
  - ホスティング先も firebase にしてしまったほうが構成が簡素になるし開発時にハマりが少ないだろうという狙い
  - これは破壊的変更に該当すると思ったので、メジャーバージョンを上げたらよいと思った

## 進め方

- mobu をベースにする
- 別のリポジトリを作る
  - 最初のうちはドラスティックに変更が入るので、main がぶっ壊れる (ホスティングが壊れる) ことが予想される
  - 既存の mobu は生かしておきたい。つまり触らないようにしたい、というのが別リポジトリを作る理由
  - mobu-of-the-world/mobu-v2 でもいいが、mobu-of-the-world/mobbu とかにして「b の数でバージョンを表す」というのをおもいついたがどうか
- pankona が mobu-v2 のために firebase project を作る。これは他の人と共有するプロジェクトになることを想定しておく。
  - 無料でいけるところまでいく
- とりあえず pankona が「認証」「なんとなく情報共有できる」くらいまでつくる
  - main に直で突っ込んだりするかもしれない
  - 一段落したら pull request 駆動に切り替える
- なんとなく動いたら、mobu (v1) は discon にする

**Comment by pankona** [comment]
@kachick 

Hi, this is mobu v2 proposal!

**Comment by geckour** [comment]
s/動機/同期/

**Comment by pankona** [comment]
@geckour Thank you!

**Comment by kachick** [comment]
機能として同期できれば勿論嬉しいとは思うのですが、 firebase が適切なのかはよくわかりませんでした！

https://github.com/kachick/mobu-elm を v2 のコードベースに使えないかなという野望もあるけれど、自分でその辺をやるイメージがあまり湧いていないのでとりあえず進めてもらうのは大歓迎です！

**Comment by kachick** [comment]
https://github.com/mobu-of-the-world/mobu/pull/727 で firebase に差し換えと、https://github.com/mobu-of-the-world/mobu/discussions/775 で https://github.com/mobu-of-the-world/emobu (旧 mobu-elm) 作ったりしたんですが、この issue の持って行き方はどうするんでしょうか
firebase project を僕の方で作った状態なので、static hosting 以外やるなら別途用意してもらったほうが良いかもしれない。(どのみち別リポジトリなのかなとは思いつつ)

機能としてセッション共有は面白そうな気もするので、 emobu 側に気が向いたら入れて見るかもしれんけど・・・

**Comment by kachick** [comment]
@pankona https://github.com/mobu-of-the-world/mobu/discussions/48#discussioncomment-537234 と自身で言ってたわけなので close しておきます！ 😤 

実際のコントリビューターを考えると完全禁止は不便すぎる気もするし、そもそもリポジトリをわけようかみたいな横断的な話をしていることも含めて、日本語会話 専用のリポジトリや GitHub discussion なり discord 作るのが良いのでは。そちらでの再復活は歓迎です！

**Comment by pankona** [comment]
英語にトランスファーしないとダメだぞということかしらね！承知です！ｗ
