### ISSUE TITLE
dependabot PRs can't be merged with the CI 🔴 

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#391]
@pankona 

CI is 🔴 

<img width="726" alt="スクリーンショット 2022-05-13 114253" src="https://user-images.githubusercontent.com/1180335/168201059-11160f7c-80ef-4123-ada4-2051c3a13440.png">
<img width="740" alt="スクリーンショット 2022-05-13 114313" src="https://user-images.githubusercontent.com/1180335/168201066-f481c4f0-9f80-46dc-b551-5c6fc77520b3.png">

**Comment by pankona** [comment]
oh...! Could you address the issue!?

**Comment by kachick** [comment]
Looks failing in netlify. I don't have tne access right and knowledge. On the otherhand, the issue came from Node version.
So I'll try a bit.👌

**Comment by kachick** [comment]
Some failling PRs looks already merged as https://github.com/mobu-of-the-world/mobu/pull/373
[mergery](https://github.com/apps/mergery) looks not stable 🤔
