### ISSUE TITLE
Drop Atomic Design structure

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#429]
I don't feel any benefit from current directory structure.
We don't have any designer specialist, all contributors can update codes directly.
Utils will be growing up because no directory exists for common and functional codes.

How about change it? 🤔 

🇯🇵  https://zenn.dev/brachio_takumi/articles/2ab9ef9fbe4159

**Comment by pankona** [comment]
Nice issue. I like bullet-proof react directory structure than current one.
Do you have another suggestions? If no, let's start to refactoring!

**Comment by kachick** [comment]
Agreed this.

https://react-file-structure.surge.sh/
https://mobile.twitter.com/dan_abramov/status/1027248875072114689

>It is a guideline though. It means literally “start by putting everything in one file; when it feels like it’s annoying, start splitting them up; what THAT gets annoying, maybe add some folders”.

We should start flat structure as possible.
