### ISSUE TITLE
Use CSS modules

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#445]
We are using very simple names for CSS classes as a pure css.
I'm positive to use pure css for this project, However I always aflaid the conflict.

So replacing to CSS Modules is a reasonable way, I think.
No adding dependencies is needed, https://github.com/mobu-of-the-world/mobu/pull/444/commits/991f0f536e8262adc8a19b22b34c42ccf5983074 is just the task.

It might be deprecated as a https://github.com/webpack-contrib/css-loader/issues/1050#issuecomment-592541379, but still keeping less cost even if it will be dropped.

**Comment by kachick** [comment]
@pankona FYI: https://developer.hatenastaff.com/entry/2022/09/01/093000

**Comment by pankona** [comment]
reading now
