### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by kachick** [mobu-of-the-world/mobu#72]
ref: https://github.com/verdaccio/verdaccio/issues/237

At the moment there is no organization logo. Please add proposals to this ticket and vote.

A candidacy is here.

![image](https://user-images.githubusercontent.com/1180335/112846306-dffe6f80-90e0-11eb-834d-fe3c88ea9eaf.png)

Drawn by @pankona's wife and colored by @ujihisa

**Comment by pankona** [comment]
Did it!
![image](https://user-images.githubusercontent.com/6533008/112846814-6a46d380-90e1-11eb-8cde-800194038ef5.png)

**Comment by kachick** [comment]
I have not yet voted to it 😬

**Comment by pankona** [comment]
Thanks!
